spring:
  datasource:
    url: jdbc:mysql://localhost:3306/moody
    username: root
    password: 0803
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MariaDBDialect
    hibernate:
      ddl-auto: create
    show-sql: true

#  thymeleaf:
#    enabled: true
#    prefix: classpath:/templates/
#    suffix: .html
#    mode: HTML
#    cache: false